# Generated by Django 3.0.3 on 2020-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_thumb', models.CharField(max_length=100)),
                ('video_name', models.FileField(upload_to='media')),
            ],
        ),
    ]
