# Generated by Django 3.0.3 on 2020-02-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_thumb',
            field=models.ImageField(upload_to=''),
        ),
    ]
