# Generated by Django 3.0.3 on 2020-02-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200215_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
