# Generated by Django 3.0.3 on 2020-02-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_name',
            field=models.FileField(default='media/profile.jpeg', upload_to='media'),
        ),
    ]
