# Generated by Django 3.0.3 on 2020-02-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200217_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos_data',
            name='Likes',
        ),
        migrations.CreateModel(
            name='post_likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Users')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Videos_Data')),
            ],
        ),
    ]
