# Generated by Django 3.0.3 on 2020-02-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200221_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post_likes',
        ),
    ]
