# Generated by Django 3.0.3 on 2020-02-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_likes',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post_likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post_likes',
            name='video',
        ),
        migrations.AlterField(
            model_name='post_likes',
            name='likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Users'),
        ),
    ]
