# Generated by Django 3.0.3 on 2020-02-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20200221_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos_data',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='post_likes',
        ),
    ]
