# Generated by Django 3.0.3 on 2020-02-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200222_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos_data',
            name='Dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
