# Generated by Django 3.0.3 on 2020-02-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20200223_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos_data',
            name='Comments',
            field=models.CharField(max_length=1000),
        ),
    ]
